
modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
#issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="talismans" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Talismans" #mandatory
#updateJSONURL="http://myurl.me/" #optional
#displayURL="http://example.com/" #optional
logoFile="icon.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
# A text field displayed in the mod UI
authors="cnlimiter" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''

'''
[[dependencies.talismans]] #optional
   modId="forge" #mandatory
   mandatory=true #mandatory
   versionRange="[40,)" #mandatory
   ordering="NONE"
   side="BOTH"
# Here's another dependency
[[dependencies.talismans]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.18.2,1.19)"
   ordering="NONE"
   side="BOTH"
